### ISSUE TITLE
Delta State vs Op CRDT

### ISSUE THREAD

**Issue by jsimnz** [ipfs/go-ds-crdt#13]
This implementation of the MerkleCRDT paper uses a delta state based ORSet CRDT, however the MerkleCRDT paper states that you could use a delta state CRDT, or an Op based CRDT, since the casual ordering property required for op based is solved when structured as a MerkleDAG.

Just wondering if there was a specific reason you went with the delta state implementation.

Thanks

**Comment by hsanjuan** [comment]
I found the semantics of delta-states are slightly nicer (i.e. batching is just merging several deltas). Other than that, in practice they are almost the same.

**Comment by jsimnz** [comment]
Great, thanks for the quick response. Make sense!
