### ISSUE TITLE
Is there any mechanism to subscribe to data changes for keys in the Datastore?

### ISSUE THREAD

**Issue by christopher-wong** [ipfs/go-ds-crdt#178]
Hey there! 

It appears that current `go-ds-crdt` storage interface is really designed to support unary Get/Put/Query operations at the Datastore level and the underlying Broadcaster is used to sync those changes to other nodes.

Is there a recommended pattern or interface that would allow subscribing to a stream of updates for specific key(s)? If the Put operations for new keys are being broadcast to other nodes by the Broadcaster in order to keep the CRDT in sync, would it be possible to subscribe to these change operations at the Datastore?

The API might look like:
```
func (store *Datastore) Subscribe(ctx context.Context, key ds.Key) (chan []byte, err error)
```

**Comment by hsanjuan** [comment]
Not for specific keys. But when you initialize the datastore you need to pass in an Options object. In this object you can set a PutHook that will notify you of every key updated. You can then, with your own logic, filter for those you are interested in.

https://pkg.go.dev/github.com/ipfs/go-ds-crdt#Options

**Comment by christopher-wong** [comment]
I'll give that a try, thanks!
