### ISSUE TITLE
go-ds-crdt.Datastore does implement latest go-datastore 

### ISSUE THREAD

**Issue by kishansagathiya** [ipfs/go-ds-crdt#20]
A new method was added to the Datastore interface
`Sync(prefix Key) error`

**Comment by yf33** [comment]
mac@mac distribution % go get github.com/ipfs/go-ds-crdt  
# github.com/ipfs/go-ds-crdt
/Users/mac/go/pkg/mod/github.com/ipfs/go-ds-crdt@v0.1.7/crdt.go:38:5: cannot use (*Datastore)(nil) (type *Datastore) as type datastore.Datastore in assignment:
        *Datastore does not implement datastore.Datastore (missing Sync method)
/Users/mac/go/pkg/mod/github.com/ipfs/go-ds-crdt@v0.1.7/crdt.go:39:5: cannot use (*Datastore)(nil) (type *Datastore) as type datastore.Batching in assignment:
        *Datastore does not implement datastore.Batching (missing Sync method)
/Users/mac/go/pkg/mod/github.com/ipfs/go-ds-crdt@v0.1.7/crdt.go:486:32: undefined: dshelp.CidToDsKey
/Users/mac/go/pkg/mod/github.com/ipfs/go-ds-crdt@v0.1.7/heads.go:34:28: undefined: dshelp.CidToDsKey
/Users/mac/go/pkg/mod/github.com/ipfs/go-ds-crdt@v0.1.7/heads.go:138:19: undefined: dshelp.DsKeyToCid

**Comment by hsanjuan** [comment]
Hi @yf33 , there is ongoing work here #22 . But if you are using a modern version of Go, go get should use Go modules to pick the right version of things.

**Comment by ncabatoff** [comment]
This can be closed now I think, can't it?
