### ISSUE TITLE
globaldb example does not exit

### ISSUE THREAD

**Issue by akakream** [ipfs/go-ds-crdt#202]
**Description**

The [globaldb example](https://github.com/ipfs/go-ds-crdt/blob/master/examples/globaldb/globaldb.go) does not exit when I enter the command `exit` or `quit`.

**Possible problem**

I believe the problem is when closing the crdt [here](https://github.com/ipfs/go-ds-crdt/blob/a89bd4f2ad16f31284ae854c621166c616848598/examples/globaldb/globaldb.go#L177). Maybe it gets stuck at [here](https://github.com/ipfs/go-ds-crdt/blob/a89bd4f2ad16f31284ae854c621166c616848598/crdt.go#L1112)?

**Comment by akakream** [comment]
Any update on this?

In the docs it says the following [here](https://github.com/ipfs/go-ds-crdt/blob/a89bd4f2ad16f31284ae854c621166c616848598/crdt.go#L1112):
`// Close shuts down the CRDT datastore. It should not be used afterwards.`

What does `It should not be used afterwards.` mean?

**Comment by hsanjuan** [comment]
> What does `It should not be used afterwards.` mean?

That means that the store should not be used (i.e. add/remove stuff) after being closed.

I can reproduce the issue. Will fix asap.

**Comment by hsanjuan** [comment]
Fixed in c5b4332.
