### ISSUE TITLE
Please close the psubTopic

### ISSUE THREAD

**Issue by wenyue** [ipfs/go-ds-crdt#227]
Please close the `psubTopic` when the context is done.

**Comment by hsanjuan** [comment]
Can you be more specific/provide more details?

**Comment by wenyue** [comment]
In the NewPubSubBroadcaster function，we join and create a psubTopic object, and this object should be closed when the context is done.

**Comment by wenyue** [comment]
Any update?

**Comment by hsanjuan** [comment]
Mind sending a PR?
