### ISSUE TITLE
How to clear tombstone

### ISSUE THREAD

**Issue by wenyue** [ipfs/go-ds-crdt#228]
When I use CRDT to write a log (add and delete frequently), the database becomes larger and larger. Is there any way to really remove the tombstone data?
My current approach is that when the database reaches a certain size, build one new, I don't know if there is any other way.

**Comment by hsanjuan** [comment]
A problem with pure CRDTs is they always grow. Deleting is adding...

What you do is the best solution as long as it works for you.
