### ISSUE TITLE
Issues changing datastore from badger to redis

### ISSUE THREAD

**Issue by rahullenkala** [ipfs/go-ds-crdt#37]
Hi @hsanjuan, 
I am experimenting the Merkle CRDTs for a metadata management usecase.

Instead of using badger, I'd like to use Redis. Here is my implementation of Redis datastore: [https://github.com/rahullenkala/dsredis](https://github.com/rahullenkala/dsredis)

The data structure of the metadata is a simple mapping of string (Key) to array of strings (Value).

` type Metadata map[string][]string `

**Problem:**

While I am running global-db  in daemon mode,Replication is not happening but I am able to put & get value in the same node .
I am wondering if there is an issue with my redis datastore implementation ?

cc @0zAND1z

**Comment by hsanjuan** [comment]
Hi @rahullenkala , have you adapted the global-db example to your needs? For example, it has a hardcoded bootstrap peer that does not really exist... You should make sure that the bootstrapping in the example hits an existing global-db peer (i.e. modify the example to not bootstrap in one peer, and then let it bootstrap to that peer from the other peer).

The example is likely a bit outdated too. If I have time I'll brush it up next week..

**Comment by rahullenkala** [comment]
Hi @hsanjuan  ,I have made required changes to global-db example we have our own  bootstrap node running.
This global-db code is working fine with any datastore (I tested with Map Datastore & Badger Datastore) except with my [redis](https://github.com/rahullenkala/dsredis) data store.
Can you please take  a look at my redis data store implementation .

**Comment by rahullenkala** [comment]
Thanks @hsanjuan ,There are problems with my redis data store implementation.

**Comment by hsanjuan** [comment]
Glad you found the issue. Note that go-datastore/test has a full datastore test suite that you can run to verify your redis datastore behaves as expected.
