### ISSUE TITLE
Put/DeleteHook func should take a context.Context

### ISSUE THREAD

**Issue by lanzafame** [ipfs/go-ds-crdt#5]
This would allow for tracing and metrics collection of the Put and Delete operations.

**Comment by hsanjuan** [comment]
It could take a context but that context would be coming from nowhere so it's the same as doing context.Background() inside it in terms of tracing.

**Comment by lanzafame** [comment]
Sorry, that is correct for tracing but not for metrics as it will allow the passing in of tags such as which peer those calls are associated with. Realistically, for tracing, I need changes to the datastore interface which isn't going to happen :(

**Comment by hsanjuan** [comment]
You can do that without having to take in a context (using one from the closure).



> Realistically, for tracing, I need changes to the datastore interface which isn't going to happen :(

Could start by requesting them in ipfs/go-datastore :)
