### ISSUE TITLE
Delete should not return error for key not found

### ISSUE THREAD

**Issue by ncabatoff** [ipfs/go-ds-crdt#62]
go-datastore's [Write](https://godoc.org/github.com/ipfs/go-datastore#Write) interface specifies for Delete:

```
    // Delete removes the value for given `key`. If the key is not in the
    // datastore, this method returns no error.
```

Yet we see in the local `Delete` method here: https://github.com/ipfs/go-ds-crdt/blob/master/crdt.go#L676

```
	if len(delta.Tombstones) == 0 {
		return ds.ErrNotFound
	}
```

This seems like a violation of the spec.

**Comment by hsanjuan** [comment]
Thanks, you are probably right.

**Comment by ncabatoff** [comment]
I'm happy to work on a fix but I need a bit of guidance, if you have time.

Is the right behaviour simply to do nothing and return nil in this case?  I'm new to this area so my intuitions are probably wrong, but it feels wrong not to record the fact that a deletion was requested. 

Suppose I create a key X and then later want to delete it, possibly via a different peer.  How can I do so reliably?  I can't poll to wait and see for when X appears, because if someone else deleted X it might never show up.  If we change the code to return nil in the empty delta.Tombstones case, and I submit the delete request for X before the peer I'm talking to has seen X appear, the delete request would be a no-op, right? 

Or am I thinking about this the wrong way?

**Comment by hsanjuan** [comment]
Returning nil and fixing any failing tests. The main issue I see is that, if there was a spec violation, the go-datastore/testing testing suite should have caught it as I would assume this case would be tested, but I might be wrong. Should check that first of all.
