### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by liminalitythree** [ipfs/go-ds-crdt#66]
The globaldb example says it lets you join a permissionless db. Is there a way to make a db that has permissions with this library. Like, only people with certain permissions can edit a certain key or something like that?

**Comment by hsanjuan** [comment]
The approach to do this I use is to register a topic validator for the PubSub instance used for the `PubSubBroadcaster`, along with message signatures and verification enabled. The pubsub message carries the peer ID of the peer that issued it, thus you can simply disregard messages from some peers (https://github.com/ipfs/ipfs-cluster/blob/7ffd18e41b550e2adbb4f59885e9003b8c7bc332/consensus/crdt/consensus.go#L163).

This is an all or nothing approach, certainly it does not support per-key permissions etc.

For more advanced use cases, I suggest https://docs.textile.io/, or one of the OrbitDB implementations, which have more advanced permission systems.

**Comment by hsanjuan** [comment]
Closing as this general support and should have been asked in discuss.ipfs.io.
